Write a query to display the author's full name and their birth date, sorted by birth date in ascending order.

Write a query to display the book title, author's full name, and the genre of books that are currently available.

Write a query to display the customer's full name, email, and birth date for customers born in the 1990s (i.e., between 1990 and 1999).

Write a query to display the total number of book orders placed by each customer. Include the customer's full name in the result.

Write a query to display the book title, author's full name, and the total revenue generated by each book (total price of all orders for that book).

Write a query to display the genre of books and the average price of books in each genre.

Write a query to display the book title and publication year for books published before the year 2020.

Write a query to display the customer's full name and the total amount they have spent on book orders. Sort the results by total amount in descending order.

Write a query to display the author's full name and the number of books they have written. Sort the results by the number of books in descending order.

Write a query to display the book title and the number of orders for each book. Sort the results by the number of orders in descending order.
